CREATE TABLE IF NOT EXISTS sessions (uid TEXT PRIMARY KEY, token_hash TEXT UNIQUE NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS scores (uid TEXT PRIMARY KEY, player TEXT NOT NULL, character TEXT NOT NULL, level INTEGER NOT NULL, total REAL NOT NULL, splits TEXT NOT NULL, stats TEXT NOT NULL, shape_hash TEXT NOT NULL, version TEXT NOT NULL, updated_at INTEGER NOT NULL, flagged INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS ranking_time ON scores(flagged,total,uid);
CREATE TABLE IF NOT EXISTS rate_limits (bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, expires INTEGER NOT NULL);
