export const shell = `<canvas id="world" aria-label="3Dアクションの世界"></canvas>
<header><a class="brand" href="./">RAKU<span>GA</span><small>ラクガキの冒険</small></a><div class="stage-label"><i></i> PLAYGROUND <span>はじまりの広場</span></div><button id="pause" aria-label="一時停止">Ⅱ</button></header>
<div class="home-panel"><section class="intro"><p class="eyebrow">YOUR LITTLE BIG ADVENTURE</p><h1>ラクガキから、<br>冒険へ。</h1><p>犬もドラゴンも、ひとつの紙から生まれる。</p><div class="pill">自由なかたち。5つの世界。ひとつの冒険。</div></section>
<div id="home-actions"><button id="draw-open" class="primary">✎ ラクガキを描く</button><button id="adventure">冒険にでかける →</button><button id="time-attack">ALL STAGES TIME ATTACK</button><div class="home-links"><button id="library-open">なかま一覧</button><button id="ranking-open">ランキング ↗</button></div></div></div><div id="save-status" role="status"></div>
<div id="player-level"></div><div id="run-hud" hidden></div><div id="objective"></div><div id="birth-banner" hidden>HELLO, WORLD ✦</div><aside id="status" role="status">世界を準備しています…</aside><div id="game-version"></div><div id="vitals" hidden><span id="health-label"></span><meter id="health" min="0" max="100" value="100" aria-label="体力"></meter></div><button id="camera-reset" aria-label="視点を北へ戻す" title="ドラッグで見回す・Q/Rで回転・Cで北へ">↻<small>北へ</small></button><div id="combat-hud" aria-live="off"></div>
<div class="controls"><div><div id="stick" aria-label="移動スティック"><span></span></div><label>MOVE</label></div><div class="buttons"><button id="action">✦<small>ACTION</small></button><button id="jump">↑<small>JUMP</small></button></div></div>
<footer>WASD / 矢印キーで移動 · SPACEでジャンプ · EでACTION</footer><div id="rotate">↻<strong>横向きにすると、もっと遊びやすい。</strong><span>スマートフォンを横向きにしてください</span></div>
<dialog id="pause-dialog"><p class="eyebrow">TAKE A BREATH</p><h2>ちょっと、ひとやすみ。</h2><p id="pause-note"></p><label class="quality-label">画質<select id="quality"><option value="low">LOW / 軽い描画</option><option value="medium">MEDIUM / おすすめ</option><option value="high">HIGH / くっきり</option></select></label><label class="sound-label"><input id="sound" type="checkbox">効果音</label><p class="camera-help">画面をドラッグで見回す · Q/Rで回転 · Cで北へ<br>リズムよくACTIONで3連撃。ジャンプ中は空中スピン。</p><button id="resume" class="primary">冒険にもどる →</button><button id="reset">スタートへ戻る</button><button id="home">広場へ戻る</button></dialog>
<dialog id="result"><p class="eyebrow">A LITTLE BRAVER THAN BEFORE</p><h2 id="result-title">ステージクリア！</h2><p id="clear-time"></p><div id="splits"></div><section id="ranking-submit" hidden><label>ランキングの表示名<input id="player-name" maxlength="20" value="ゲスト"></label><button id="submit-score">この記録を登録する</button><p id="submit-status" role="status"></p></section><button id="select-next" class="primary">ステージを選ぶ →</button></dialog>`;
export const $ = (s) => document.querySelector(s);
